### ISSUE TITLE
Release to Cargo

### ISSUE THREAD

**Issue by cwoodall** [tsabelmann/pcan-basic-sys#6]
Hello @zachatttack @thebeekeeper.

You two seem to be using this repo more than me. Should we possibly find a github group to move this to, or a piece of the rust community working on this to transfer ownership to so this can be well supported?

**Comment by thebeekeeper** [comment]
Seems like a good idea to me.  I don't use CAN on Windows a ton, but I'd be happy to help out with maintenance.
